# Generated by Django 4.2.23 on 2025-07-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='course',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='hr',
            old_name='course',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='employeeresult',
            name='subject',
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Designation',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='project',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.designation'),
        ),
        migrations.AddField(
            model_name='project',
            name='hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hr'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.project'),
        ),
        migrations.AddField(
            model_name='employeeresult',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.project'),
        ),
    ]
